### ISSUE TITLE
Process constant values are platform-dependent on Linux

### ISSUE THREAD

**Issue by matoro** [ruby/spec#1150]
Hi, in `core/process/constants_spec.rb` there are a few tests which explicitly test the values of the `RLIMIT_*` constants.  These will fail on platforms which use different values for these constants.  Example test failure on SPARC:

```
1)
Process::Constants has the correct constant values on Linux FAILED
Expected 7 == 6
to be truthy but was false
/var/tmp/portage/dev-lang/ruby-3.2.3/work/ruby-3.2.3/spec/ruby/core/process/constants_spec.rb:45:in `block (3 levels) in <top (required)>'
/var/tmp/portage/dev-lang/ruby-3.2.3/work/ruby-3.2.3/spec/ruby/core/process/constants_spec.rb:3:in `<top (required)>'
```

The default value is indeed `6`:
https://github.com/torvalds/linux/blob/master/include/uapi/asm-generic/resource.h#L26-L28

But this can be overridden on a per-architecture basis, e.g. SPARC overrides it to `7`:
https://github.com/torvalds/linux/blob/master/arch/sparc/include/uapi/asm/resource.h#L11-L16

At a quick glance, both Alpha and MIPS are also affected by this specifically for `RLIMIT_NPROC`, but other architectures may be affected for other resource constants.

**Comment by matoro** [comment]
> Could you make a PR adjusting the guards in https://github.com/ruby/spec/blob/master/core/process/constants_spec.rb ? `platform_is str` checks if `str` is a substring of `RUBY_PLATFORM`.

How specifically would you want to restrict this?  As noted, there are multiple architectures which have different values under Linux, and they differ in which constants have different values as well, so the code could get quite complex.

Fundamentally I don't understand the purpose of this test of compile-time constants against hardcoded values, unless you need to perform some sort of manual change when they update?  I believe the fundamental purpose of this test is mistaken.

**Comment by eregon** [comment]
I think a simple approach would be to use `platform_is "x86_64-linux" do` around them instead of just `platform_is :linux do`.

There is some value to check that the values are correct, for instance that there is no mistake in https://github.com/oracle/truffleruby/blob/60344290e312370a937cbf46b0a9099158318edc/src/main/ruby/truffleruby/core/process.rb#L37-L67 and other Ruby implementations.

I can see your POV too, maybe we should only check that they are `Integer` or so.
