### ISSUE TITLE
Using eval for expectations prevents testing other execution modes

### ISSUE THREAD

**Issue by headius** [ruby/spec#1152]
In https://github.com/ruby/spec/commit/e922a1717ee2524d3dc789ab1f12db679b8e5711 all of the pattern specs were switched to using `eval`, presumably because TruffleRuby could not parse/compile all of the pattern forms being tested. Unfortunately this means that these examples are only ever being tested in eval.

On JRuby, this means they will never be run through our bytecode JIT, which does not compile bare eval contents. This led to https://github.com/jruby/jruby/issues/8283 being missed until now. I believe this would also affect any testing of CRuby's YJIT, since I believe they also only JIT bodies of code, not eval snippits.

I understand the difficulty of running specs when syntax is not yet supported, but this is not a good solution. At the very least the contents of the eval should include a method or block wrapper, so that implementations that JIT only on those edges can still force JIT to happen for testing.

**Comment by headius** [comment]
An attempt to improve this is in #1153, but I could not evaluate all cases into methods because some depend on captured variables. I would be happier if we could eliminate the evals altogether.

**Comment by eregon** [comment]
> presumably because TruffleRuby could not parse/compile all of the pattern forms being tested.

The original reason is because 2.5/2.6 cannot parse it.
But then indeed it we needed to keep as long as TruffleRuby could not parse pattern matching.
Since 3.0 is minimum now and TruffleRuby can parse (and supports) pattern matching I think there is no need to keep in `eval`.
Could you remove the `eval`s from that file?
