### ISSUE TITLE
Should we be using evaluate specs?

### ISSUE THREAD

**Issue by chrisseaton** [ruby/spec#181]
Such as

https://github.com/ruby/rubyspec/blob/master/language/method_spec.rb#L734

```ruby
    evaluate <<-ruby do
        def m(a=1, *) a end
      ruby

      m().should == 1
      m(2, 3, 4).should == 2
    end
```

These generate very awkward spec name such as 

```
"A method assigns local variables from method parameters for definition \n    def m(*, **k) k end"
```

**Comment by vais** [comment]
LOL https://github.com/opal/opal/blob/master/spec/filters/bugs/unboundmethod.rb#L7-L19

**Comment by elia** [comment]
Did it for other reasons, but still relevant: https://github.com/opal/opal/blob/master/spec/opal/core/arity_spec.rb

**Comment by eregon** [comment]
I don't like `evaluate` so much either, but I can guess the reasons to use it for argument-related specs such as in `method_spec.rb`:

* These specs would have a rather cumbersome description for stuff like ` def m(a=1, (b, *c), (*d, e))`.
* Some of these specs use required keyword args, which are not syntactically valid in 2.0, which means `eval` is needed.

The link from @chrisseaton shows indeed one of the many specs that could just be done normally since the syntax is compatible with all versions (2.0 - trunk).

So, converting them to more readable English descriptions would be good.
```
A method assigns local variables from method parameters for optional and rest arguments
```
```ruby
    it "for optional and rest arguments" do
      def m(a=1, *)
        a
      end

      m().should == 1
      m(2, 3, 4).should == 2
    end
```
(The `def m` defines on the per-describe context which is fine by me)

**Comment by chrisseaton** [comment]
I think the situation could be improved simply by automatically flattening the string's multiple lines into one.

```
fails:"A method assigns local variables from method parameters for definition \n    def m(*, **k) k end"
fails:A method assigns local variables from method parameters for definition def m(*, **k) k end
```

**Comment by eregon** [comment]
The purpose of the current approach is for nice output with the specdoc formatter:
```
$ mspec -fs language/lambda_spec.rb 
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

A lambda literal -> () { }
- returns a Proc object when used in a BasicObject method
- does not execute the block
- returns a lambda
- has its own scope for local variables

A lambda literal -> () { } assigns no local variables
- for definition 
    @a = -> { }
    @b = ->() { }
    @c = -> () { }
    @d = -> do end

A lambda literal -> () { } assigns variables from parameters
- for definition 
    @a = -> (a) { a }
- for definition 
    @a = -> ((a)) { a }
```

**Comment by eregon** [comment]
One easy fix for that single-line of code case, would be to String#chomp before checking if the source contains "\n", the output would then be:
```
A method assigns local variables from method parameters
- for definition 'def m(a) a end'
...
- for definition 
    def m(a, (b, (c, *d, (e, (*f)), g), (h, (i, j))))
      [a, b, c, d, e, f, g, h, i, j]
    end
- for definition 'def m(a, b=1) [a, b] end'
...
- for definition 'def m(a=1, *) a end'
```
and the tag:
```
fails:"A method assigns local variables from method parameters for definition 'def m(a=1, *) a end'"
```

Would that be better?
I can do the change in mspec, but obviously tags will need to be adapted to match the new spec descriptions.

**Comment by chrisseaton** [comment]
Yes that tag is better I think. That's all I cared about.

**Comment by eregon** [comment]
@elia @vais Do you agree with this slightly changed format for tags of `evaluate` specs?
It only applies to single-line of code `evaluate`, multi-line keep the same format, for nice output with `-fs` and so that `evaluate` is just a fancy `it`.

**Comment by elia** [comment]
fine by me, we'll update our tags

**Comment by vais** [comment]
:+1:

**Comment by eregon** [comment]
I committed the simple fix for one-line of code specs.
