### ISSUE TITLE
Incorrect expectations for ARGF.binmode behavior on Windows

### ISSUE THREAD

**Issue by vais** [ruby/spec#207]
These two expectations are incorrect: https://github.com/ruby/spec/blob/master/core/argf/binmode_spec.rb#L15-L29

Basically, there is a file with Unix-style line breaks, and it is expecting that setting `binmode` will convert these Unix-style line endings into Windows-style line endings. That does not make any sense, because it's just not what `binmode` does. Per http://ruby-doc.org/core-2.0.0/ARGF.html#method-i-binmode

> Puts ARGF into binary mode. Once a stream is in binary mode, it cannot be reset to non-binary mode. This option has the following effects:
* Newline conversion is disabled.
* Encoding conversion is disabled.
* Content is treated as ASCII-8BIT.

The proof is in the pudding:
```
C:\Users\Administrator\GitHub\spec>C:\Ruby\ruby-2.2.4-i386-mingw32\bin\ruby.exe -ve "ARGF.binmode; p ARGF.gets" C:\Users\Administrator\GitHub\spec\core\argf\fixtures\bin_file.txt
ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]
"test\n"
```
And here is the same result using ruby 1.8.7 (cause I wondered where these expectations came from, perhaps this is how it used to work on 1.8? But no.)
```
C:\Users\Administrator\GitHub\spec>C:\Ruby\ruby-1.8.7-p374-i386-mingw32\bin\ruby.exe -ve "ARGF.binmode; p ARGF.gets" C:\Users\Administrator\GitHub\spec\core\argf\fixtures\bin_file.txt
ruby 1.8.7 (2013-06-27 patchlevel 374) [i386-mingw32]
"test\n"
```

Ok, so to fix this and test `ARGF.binmode` properly, we need to add another fixture - a text file (named `win_file.txt`) containing Windows-style line breaks, then reading it in `binmode` should give us Windows-style line breaks, and reading it without `binmode` should give us Unix-style line endings:

```
C:\Users\Administrator\GitHub\spec>C:\Ruby\ruby-2.2.4-i386-mingw32\bin\ruby.exe -ve "ARGF.binmode; p ARGF.gets" C:\Users\Administrator\GitHub\spec\core\argf\fixtures\win_file.txt
ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]
"test\r\n"

C:\Users\Administrator\GitHub\spec>C:\Ruby\ruby-2.2.4-i386-mingw32\bin\ruby.exe -ve "p ARGF.gets" C:\Users\Administrator\GitHub\spec\core\argf\fixtures\win_file
.txt
ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]
"test\n"
```
@eregon unless there are any objections, I will be sending a PR for this, LMK...

**Comment by vais** [comment]
Just realized that the reason for this working incorrectly may have something to do with git or something else along the line having converted the line endings in the fixture file `bin_file.txt` from `\r\n` to `\n`.

**Comment by vais** [comment]
Yep, that was it - there's nothing wrong with the code, the problem was with the data (the fixture file). I replaced `\n`s with `\r\n`s in `bin_file.txt` and the spec makes sense again :smile: 
```
C:\Users\Administrator\GitHub\spec>..\mspec\bin\mspec core/argf/binmode_spec.rb
ruby 2.0.0p247 (2013-06-27) [i386-mingw32]
[| | ==================100%================== | 00:00:00]      0F      0E

Finished in 0.171600 seconds

1 file, 4 examples, 6 expectations, 0 failures, 0 errors, 0 tagged
```
One down, hundreds more to go :beers:

**Comment by eregon** [comment]
Good find! 356fa4fb3e40f3a739c10f256d59a0885bfe39a7 seems the culprit.
