### ISSUE TITLE
Skip the entire ARGF.read_nonblock spec on Windows

### ISSUE THREAD

**Issue by vais** [ruby/spec#213]
Hi, @eregon, what's the "right" way to skip the entire https://github.com/ruby/spec/blob/master/core/argf/read_nonblock_spec.rb on Windows? 

`ARGF.read_nonblock` is not supported on Windows (https://bugs.ruby-lang.org/issues/5954#note-5), and it does not raise a nice exception like, e.g. `fork` does on Windows.

`fork` spec basically wraps most of the file in a "not on windows" block, but there's also a small "on windows" block there. Since the entire `ARGF.read_nonblock` spec can be skipped on Windows, is there a better way than to wrap the entire spec in a "not on windows" block, indenting the whole thing 2 spaces?

**Comment by eregon** [comment]
Hi @vais,
Wrapping everything in `platform_is_not :windows do` is the right way (even the top-level `describe`).
Change of indentation is not optimal, but it greatlys helps to see where a guard applies (for example for ruby version guards). Maybe we could have a shortcut notation, but I think this would be non-trivial to implement or have other drawbacks, so I'd rather stick with the current simple approach.

**Comment by vais** [comment]
Thanks @eregon it makes sense. Yeah, I was hoping to keep the diff simple :wink:

**Comment by eregon** [comment]
We can always ignore space changes for the diff :smiley:  (git `-w` or GitHub `?w=1`)

**Comment by vais** [comment]
@eregon thanks for the `git diff -w` and `?w=1` tip, I learned something today :smile:
