### ISSUE TITLE
Conditional regular expressions

### ISSUE THREAD

**Issue by backus** [ruby/spec#254]
Rubyspec does not seem to contain any tests for conditional regular expressions like the following:

**conditional with positional capture group**

```ruby
/\A(foo)?(?(1)(T)|(F))\z/
```

**conditional with named capture group**

```ruby
/\A(?<word>foo)?(?(<word>)(T)|(F))\z/
```

**conditional with only a true branch**

```ruby
# positional
/\A(foo)?(?(1)(T))\z/

# named
/\A(?<word>foo)?(?(<word>)(T))\z/
```

Does rubyspec try to cover all regular expression syntax? If so I would be happy to PR the necessary tests

**Comment by eregon** [comment]
Yes, more coverage is always better :smiley: I'll welcome any PR you have.
It seem it would go here: https://github.com/ruby/spec/blob/master/language/regexp_spec.rb

**Comment by eregon** [comment]
@backus Any update on this?

**Comment by backus** [comment]
@eregon I forgot about this sorry about that. See #299
