### ISSUE TITLE
Support to r55024 (Unifying Biignum/Fixnum to Integer)

### ISSUE THREAD

**Issue by hsbt** [ruby/spec#256]
Ruby 2.4.0 has been unified bignum/fixnum to Integer at https://github.com/ruby/ruby/commit/f9727c12cc8fbc5f752f5983be1f14bb976e5a13

spec is boken now. We need to solve it. ref https://travis-ci.org/ruby/ruby/builds/130761218

**Comment by eregon** [comment]
Awesome, although it probably shouldn't segfault, right? :)
My understanding is we can keep most of the C-API unchanged and still allow its usage, while at the Ruby level Fixnum = Bignum = Integer.

**Comment by akr** [comment]
It is because ensure_bignum (optional/capi/bignum_spec.rb) can return fixnum now
because Bignum#coerce is moved to Integer#coerce and it returns fixnum as fixnum.

**Comment by eregon** [comment]
Should `rb_big2long` and such also handle Fixnums now or not?

**Comment by eregon** [comment]
We should rewrite some of these specs since they rely on the wrong assumption that Bignum.coerce(Fixnum) gets a Bignum. `bignum_value`, `fixnum_min` and `fixnum_max` should be used instead.

**Comment by eregon** [comment]
I made an intermediate fix erroring if Bignum#coerce(Fixnum) does not return a Bignum and indeed it stops to segfault.

**Comment by akr** [comment]
It is possible to modify rb_big2long and other bignum functions to support fixnum too.

But I don't consider it currently because:
- the function name contains "big".  It means the function is dedicated for bignum
- I'm not sure that this SEGV problem is unique to rubyspec or common for many libraries.

**Comment by eregon** [comment]
I see, indeed this seems a bit specific to ruby/spec for me as well. People are unlikely to call `rb_big*` on non-Bignums in C code.
I'll fix the specs, my first attempt was a miss, there is no way to know whether a value is in Fixnum range anymore now :smiley:

**Comment by eregon** [comment]
Specs should pass on trunk now.

**Comment by eregon** [comment]
http://rubyci.org/ is happy so I'll close this.
Thanks for raising the issue so I could help to fix this in a timely manner 😃

**Comment by hsbt** [comment]
👍  Thank you @eregon and @akr
