### ISSUE TITLE
How to write specs that are used from a given commit and up?

### ISSUE THREAD

**Issue by duerst** [ruby/spec#264]
At https://github.com/ruby/spec/pull/263, I removed some specs for Ruby 2.4 and up. Eventually, there should be some new, somewhat different, tests for Ruby 2.4. When should these be provided? How can I write a spec so that we can check it as soon as possible, but avoid that some of the specs fail on trunk before the new features go live, or on older versions of trunk before a given version/commit?

**Comment by eregon** [comment]
ruby/spec aims to test latest versions of each Ruby minor version (2.1, 2.2, 2.3) and latest MRI trunk, so do not worry about older MRI trunk, an older ruby/spec can be used if needed for that special case.

But indeed there is some synchronization problem. The usual solution is:

* Develop the spec while implementing the new feature
* Commit to ruby/ruby and make a Pull Request here (in either order)
* Merging the Pull Request after restarting the build to take the latest MRI into account

Travis CI will automatically pick the new MRI trunk as soon as it has a successful build.
(Pushing first to ruby/spec would therefore prevent successful builds of ruby/ruby until the feature is merged which of course is not ideal.)

This is the current process, which @nobu uses regularly. If not practical enough, we could maybe try to build our own MRI trunk or let ruby/ruby specify which version of ruby/spec to use.

**Comment by eregon** [comment]
So for the spec guards, use `ruby_version_is "2.4" do`, since older trunk versions need not to be taken in account. I hope I answered your question.

**Comment by duerst** [comment]
Just for the record,
   ruby_version_is "2.4" do ... end
means "version 2.4 and higher".
