### ISSUE TITLE
Update appveyor.yml to start testing Ruby 2.3.1 on Windows

### ISSUE THREAD

**Issue by vais** [ruby/spec#277]
This became possible thanks to @Azolo's valiant effort to finally push out a new RubyInstaller with 2.3.1 support, but it's still currently blocked on AppVeyor adding Ruby 2.3.1 support (https://github.com/appveyor/ci/issues/925).

**Comment by eregon** [comment]
In the mean time, it seems there already is a 2.3.0 version on AppVeyor:
https://www.appveyor.com/docs/installed-software#ruby
I'll give that at try.

**Comment by eregon** [comment]
I tried it on branch `try_appveyor_21_23`.
There are some errors: https://ci.appveyor.com/project/eregon/spec/build/318
