### ISSUE TITLE
failure on ruby trunk travis ci

### ISSUE THREAD

**Issue by nobu** [ruby/spec#288]
[r55970](https://github.com/ruby/ruby/commit/ea293952c549c61265db6ab20071fe9d83b930f1) [passed](https://travis-ci.org/ruby/ruby/builds/153524321), but
[r55972](https://github.com/ruby/ruby/commit/e79b23c12fb482856412ebdd782b6abbfb0a2cae) [failed](https://travis-ci.org/ruby/ruby/builds/153724372).
The change between these 2 revisions is actually [r55971](https://github.com/ruby/ruby/commit/51d30645a241a4441358d196165b3f7e3560df71), and should not affect Linux.
Seems caused by 03123374895c3794fc80f5f234dc87874af79ad0, 641bc0158d40438aed2c6280ecf415c1d58a710c, a102ba3391e1a9be819097b75f7f3561f0246372, a26029ceac8f831f1bc5db56b5bfb1fa652bd96d.

Just-built `ruby` may need environment variables to load `libruby` shared library, and "system" `ruby` may not exist.

**Comment by eregon** [comment]
Thank you @nobu!
Sorry for the breaking change :/
These specs are quite fragile as they try to run ruby without any environment variable.
The fix is the right one, we might just need to pass some essential variables like `$HOME` on other rubies.
