### ISSUE TITLE
setsockopt spec fail with non-linux environments.

### ISSUE THREAD

**Issue by hsbt** [ruby/spec#292]
https://github.com/ruby/spec/blob/master/library/socket/basicsocket/setsockopt_spec.rb#L189 

Above expectation fails on FreeBSD, Solaris environments on Ruby CI. ref http://rubyci.s3.amazonaws.com/freebsd82-64/ruby-trunk/log/20160904T030301Z.fail.html.gz

**Comment by eregon** [comment]
Thanks for the report, please make a PR to guard the spec so it only runs on Linux (or if there is a cross platform way to test this it's even better of course).
Otherwise I can fix it but it will take a couple days.

**Comment by eregon** [comment]
Fixed by @nurse in f0548a9a0bb7271f334a30d7c34dbd56a8764189, thanks!
