### ISSUE TITLE
Need better way to test IO#seek with > 2**32 offset

### ISSUE THREAD

**Issue by headius** [ruby/spec#296]
I attempted to make a spec for seeking with offsets > 2**32 without creating a large file.

The attempt [here](https://github.com/jruby/jruby/commit/23568373b59cf9f9ced9710add6142b29203c399) worked ok on OS X, but not on Linux.

I modified it to only run on OS X, but obviously we'd like something that runs on Linux at least.

Suggestions?

**Comment by headius** [comment]
cc @enebo

**Comment by eregon** [comment]
Maybe using a sparse file like described in https://wiki.archlinux.org/index.php/sparse_file ?
This would not work on OS X though.

We could make a helper for this in fixtures/classes.rb.

**Comment by eregon** [comment]
@headius Did you try the sparse file approach?

**Comment by eregon** [comment]
Closing this, please try the sparse file approach on Linux.
I think the helper could be in one of the fixtures files first, and if it's used in many places we can move it to mspec.
