### ISSUE TITLE
How to report a Segfault?

### ISSUE THREAD

**Issue by markburns** [ruby/spec#308]
Hi. 

I'm experiencing a segfault in my test suite for my rather complicated and probably overly ambitious project at https://github.com/markburns/delfos

(Project aim - record method calls and runtime type information in a ruby application)

I'd like to know how best to report this, given that I now have very limited time for open source and have not followed the changes in depth for the move to `ruby/spec`. So apologies up front.

#### Admittedly non-trivial replication steps (sorry)

```
#install neo4j on your system

git clone git@github.com:markburns/delfos.git
git checkout origin/support_recording_class_method_inherited
bundle install


# BEWARE this currently deletes all data in the neo4j instance at localhost:7474


bundle exec rspec lib/delfos/integration_spec.rb

```
Output - https://gist.github.com/markburns/e26481b83c91c3726a0aa497f96b16ab

#### Friendly guidance request

I have some questions - because I didn't see mention in the `CONTRIBUTING.MD`:

* Is here with a minimal case for replication the best place to report a segfault?
* Is a PR with the above preferable?
* What is the workflow? I.e. if a green build is required for a PR to be merged, does that mean a feature branch with a failing spec can only be merged after the underlying ruby issue is fixed? 
* A side question - is this suite being green a prerequisite for release of a new ruby version?

**Comment by eregon** [comment]
Hello,
You should report this to the MRI bug tracker at https://bugs.ruby-lang.org/
