### ISSUE TITLE
spec for File::TMPFILE fails on Amazon Linux

### ISSUE THREAD

**Issue by shugo** [ruby/spec#368]
spec for File::TMPFILE fails on Amazon Linux:

http://rubyci.org/logs/rubyci.s3.amazonaws.com/amazon/ruby-trunk/log/20161207T063002Z.fail.html.gz

O_TMPFILE is defined in glibc 2.19 or later:

https://github.com/bminor/glibc/commit/ffdd31816a67f48697ea4d6b852e58d2886d42ca

It may be better to test the behavior if File::TMPFILE is defined, instead of testing
the existence of the constant.

**Comment by shugo** [comment]
glibc version can be checked by `Etc.confstr(Etc::CS_GNU_LIBC_VERSION)`.

**Comment by eregon** [comment]
Thanks for the report, bdb599c should solve it.
I looked for a test in MRI for inspiration but did not find any, so I made an example based on the manpage.

**Comment by eregon** [comment]
Great idea to test the behavior if defined BTW, since presence of this feature is so hard to test otherwise

**Comment by shugo** [comment]
Thanks for the fix.
But it failed on armv7l-linux-eabihf:

http://rubyci.org/logs/rubyci.s3.amazonaws.com/scw-9d6766/ruby-trunk/log/20161207T211705Z.fail.html.gz

It may be better to skip the test if Errno::EINVAL is raised.
And It seems that Errno:EOPNOTSUPP is raised if the filesystem doesn't
support O_TMPFILE.

**Comment by eregon** [comment]
I agree for EOPNOTSUPP, but it seems EINVAL is a bug on that platform:
```
EINVAL The filesystem does not support the O_DIRECT flag.  See NOTES for more information.
EINVAL Invalid value in flags.          
EINVAL O_TMPFILE was specified in flags, but neither O_WRONLY nor O_RDWR was specified.
```
None of these should apply. `O_DIRECT` is not provided, flags are valid AFAIK and O_TMPFILE is specified with O_RDWR. Do you have any idea why it raises EINVAL?

**Comment by shugo** [comment]
> None of these should apply. O_DIRECT is not provided, flags are valid AFAIK and O_TMPFILE is specified with O_RDWR. Do you have any idea why it raises EINVAL?

Besides these cases, EINVAL occurs if O_CREAT is specified with O_TMPFILE, but O_CREAT
is not specified in bdb599ca....

glibc 2.19 seems to have the following bug, but I'm not sure it's related.

https://lists.debian.org/debian-glibc/2016/09/msg00037.html
http://permalink.gmane.org/gmane.comp.lib.glibc.alpha/46271

**Comment by eregon** [comment]
> Besides these cases, EINVAL occurs if O_CREAT is specified with O_TMPFILE, but O_CREAT
is not specified in bdb599c....

Indeed, I noticed that as well when trying with `IO.sysopen`.

**Comment by eregon** [comment]
5254fba allows both errors.
