### ISSUE TITLE
Repeatability of RubySpec

### ISSUE THREAD

**Issue by mgaudet** [ruby/spec#381]
`mspec` provides the `-R` flag to run specs multiple times. From the perspective of JIT Compiler testing, this is quite useful, as it will allow exercising many more paths than possible with just compile-before-execution. 

However, `ruby/spec` currently explodes if `-R` is passed:  ie, 

```
$ ./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems -r./x86_64-linux-fake ./spec/mspec/bin/mspec run -B ./spec/default.mspec -R 2

```

Puts out huge quantities of error. 

I think there's a philosophical question here about spec: Should specs be modified to be idempotent to support repetition? 

Or, is this instead a problem that should be addressed via `mspec`'s runner?

**Comment by eregon** [comment]
It seems a good part of the specs pass, but indeed some exhibit bad behavior.
(`core/array` seems to work just fine for example)
Specs should be idempotent, and therefore the ones that are not should be fixed.

As usual, it's hard to keep all configurations running as it would mean explosion of configurations.

Some autoload specs seems to hang, if I exclude them I get 140 failures and 27 errors, which is a lot but many seems to be similar:
```
mspec -R 2 -E autoload
```

I'll have a look at some of these specs. Of course, any patch to help is welcome :smiley:

**Comment by mgaudet** [comment]
Awesome. I'll look into providing some (may not be shortly) -- but I wanted to have a philosophical go-ahead that it was worth chasing :D 

Thanks!

**Comment by eregon** [comment]
I fixed the cases in `language`, so `mspec -R2 language` works now :smiley:

**Comment by eregon** [comment]
I fixed `library` and `optional` as well, so only `core` remains with 33 failures with `-R2`.

**Comment by mgaudet** [comment]
O.o Thanks so much! 

I haven't even looked at this yet. 😮

**Comment by eregon** [comment]
The whole suite now runs with `-R2`, and it's tested in Travis to make sure we don't regress!
