### ISSUE TITLE
Build broken on ruby/ruby branches

### ISSUE THREAD

**Issue by hsbt** [ruby/spec#440]
I got build errors on branches of ruby/ruby.

* 2.4 https://travis-ci.org/ruby/ruby/builds/238065839
* 2.3 https://travis-ci.org/ruby/ruby/builds/238065845
* 2.2 https://travis-ci.org/ruby/ruby/builds/238065891

It is caused by CAPI changes of ruby/spec maybe.

**Comment by eregon** [comment]
Thanks, I'll take a look.

**Comment by eregon** [comment]
b2e6a3a2bb0dacf4131152ac34310e84cb512923 fixed 2.4, I restarted the build and it's now green.
I'm restarting the 2.3 build to see if it's fixed too.

**Comment by eregon** [comment]
a34d2a57ebe5f301ce95c7afaa80e1a0cc1a0f32 should fix all cases, I restarted all builds, let's see.

**Comment by eregon** [comment]
All are fixed!
