### ISSUE TITLE
Using true/false as processes to return exit status 0/1

### ISSUE THREAD

**Issue by eregon** [ruby/spec#454]
I would like to use the `true` and `false` binaries instead of a full blown ruby process just to return basic exit statuses.

But, I am not sure if there is an equivalent on Windows.
@MSP-Greg do you know if there are equivalent binaries that just return a success/failure exit status on standard Windows?

It's available on AppVeyor, but that seems a full mingw environment which is quite different:
https://ci.appveyor.com/project/eregon/windows-shell/build/29

**Comment by mjago** [comment]
Information here may be relevant?

https://stackoverflow.com/questions/22046780/whats-the-windows-command-shell-equivalent-of-bashs-true-command

**Comment by MSP-Greg** [comment]
@eregon 

> It seems there is no easy solution

As mentioned, using exit is probably the only way, but that requires a script.

The issue of the MinGW/MSYS2 environment's inclusion in Appveyor is the cause of one failure I have in test-all, as without usr/bin in the path, the test passes on windows.

**Comment by eregon** [comment]
@MSP-Greg Does
```ruby
Process.wait spawn("exit 1")
p $?
```
works as expected in the Windows shell? (and the same with `0`)

It [works fine](https://ci.appveyor.com/project/eregon/windows-shell/build/30) on AppVeyor but that's probably due to MinGW.

**Comment by MSP-Greg** [comment]
@eregon 

Interesting.  I don't see any reference to msys or mingw in the appveyor log, but there is
```
/c/Program Files/Amazon/AWSCLI:/cmd:/usr/bin
```

Output from a msys2 bash shell:
```
$ /c/ruby25_64/bin/ruby -e "Process.wait spawn('exit 1') ; puts 'here' ; puts $?"
here
0
```

Output from a windows cmd window:
```
E:\>ruby -e "Process.wait spawn('exit 1') ; puts 'here' ; puts $?"
here
pid 6352 exit 1
```

**Comment by eregon** [comment]
I think in the msys2 bash shell, bash might have substituted the $? by 0, could you try with single quotes?
```
/c/ruby25_64/bin/ruby -e 'Process.wait spawn("exit 1") ; puts "here" ; puts $?'
```

**Comment by eregon** [comment]
But the fact it works on Windows' cmd window is a good sign, this seems portable :smiley:

**Comment by MSP-Greg** [comment]
> I think in the msys2 bash shell, bash might have substituted the $? by 0, could you try with single quotes?

You are correct.  Sorry, kind of wondered about that, as I don't normally use the bash shell...

```
$ /c/ruby25_64/bin/ruby -e 'Process.wait spawn("exit 1") ; puts "here" ; puts $?'
here
pid 3064 exit 1

$ /c/ruby25_64/bin/ruby -e 'Process.wait spawn("exit 0") ; puts "here" ; puts $?'
here
pid 4568 exit 0
```
