### ISSUE TITLE
Matching up Ruby version to spec version

### ISSUE THREAD

**Issue by Epigene** [ruby/spec#460]
Hi!

I ran into a gotcha where I was using Ruby 2.1.0 and running specs on master ended with some failures.
It would be useful to know which commit(s) or releases of this spec repo correspond to which Ruby version.

**Comment by eregon** [comment]
Basically only the latest releases of Ruby 2.2.x and more recent are supported with the latest ruby/spec.
This is sort of documented in the [.travis.yml](https://github.com/ruby/spec/blob/master/.travis.yml).
It should be better documented in the README (contributions welcome).

MSpec, the tool to run the specs actually also requires Ruby 2.2. I'll add a more explicit check there so it fails early and clearly if the Ruby used is too old.

**Comment by eregon** [comment]
I tried to clarify the Ruby version requirements in MSpec and here, see the linked commits.

**Comment by Epigene** [comment]
Thank you.
