### ISSUE TITLE
Suggestions for testing options in Net::FTP.new

### ISSUE THREAD

**Issue by AndrewSpeed** [ruby/spec#534]
I'm working on new specs for [the options hash for new](https://ruby-doc.org/stdlib-2.4.0/libdoc/net/ftp/rdoc/Net/FTP.html#method-c-new) made available in Ruby 2.4 as part of #473, and I wanted to get some input on how to approach testing the `ssl` option, as this has a branching condition based on whether `OpenSSL::SSL` is defined. Do we have any examples in the codebase where something similar is being tested?

Apologies if this isn't the best place for this, I didn't see any methods of communication mentioned in `contributing.md`

**Comment by eregon** [comment]
Here is a somewhat similar example of YAML requiring OpenStruct in its specs:
https://github.com/ruby/spec/blob/81c9b4fe45f9b3b53ec520a3ae73e0ff9af3ff64/library/yaml/dump_spec.rb#L37-L41

**Comment by AndrewSpeed** [comment]
Perfect, thanks very much @eregon I'll try implementing that tomorrow and hopefully get a PR up shortly afterwards 🙂

**Comment by AndrewSpeed** [comment]
I'm having some difficulty testing a particular branch of the `initialize` method, namely: https://github.com/ruby/ruby/blob/trunk/lib/net/ftp.rb#L223

The problem is that I want to test that when the `ssl` option is passed without `openssl` being imported, it should raise an exception. Normally the way to do this from what I've seen is to wrap the call you expect to raise the exception in a lambda, but for this I have to make use of `ruby_exe` as you suggested. Unfortunately this only seems to return string values, rather than raising any exceptions.

I don't see any similar cases like this in the repository, do you have any suggestions on how best to approach this? One option could be to rescue the exception and then return it's string value from the `ruby_exe` call, but this doesn't feel right to me

**Comment by eregon** [comment]
> One option could be to rescue the exception and then return it's string value from the `ruby_exe` call, but this doesn't feel right to me.

That sounds like the simplest solution to me.
```ruby
ruby_exe("begin ... rescue => e; puts e.message; end").should == ...
```

But actually, this should only happen if the openssl extension is not *installed*.
That is, lib/net/ftp.rb does `require "openssl"` https://github.com/ruby/ruby/blob/5256f7752763249288662c6c5ffc5686d244a535/lib/net/ftp.rb#L23

So I think it's actually not so useful to test for this condition, it's just a sign of a broken Ruby installation with no openssl.
We generally assume the openssl extension is available in ruby/spec, it's part of the Ruby standard library.
