### ISSUE TITLE
[Ruby 2.5] FrozenError

### ISSUE THREAD

**Issue by marcandre** [ruby/spec#557]
A huge bunch on specs should be modified to spec Ruby 2.5's behavior of raising a `FrozenError` when attempting to mutate a frozen object.

Instead duplicating the affected specs and referring to `FrozenError` directly, the helper `frozen_error_class` should be used (see [this](https://github.com/ruby/mspec/pull/35)). As such, no direct mention of `FrozenError` should appear in the specs, only `frozen_error_class`.

Anyone wants to handle this?

**Comment by Atul9** [comment]
Yes, I have started working on this.

**Comment by Atul9** [comment]
In the spec description should we rename `RuntimeError` to `frozen_error_class` OR  `FrozenError` 
- raises a `RuntimeError` if the array is frozen
to 
- raises a `frozen_error_class` if array is frozen?
OR
- raises a `FrozenError` if array if frozen?

**Comment by marcandre** [comment]
Mmm, good question. Maybe simply "raises the appropriate error if the ..."

**Comment by eregon** [comment]
I think in this case it would be fine to use the new terminology (`raises a FrozenError if the array if frozen`), what do you think @marcandre ?
I was thinking to `raises a frozen error if the array if frozen` but that's just misleading (as if the error was frozen).
`raises the appropriate error if the array if frozen` doesn't say which so then we could just be generic and say `raises an error if the array if frozen`.

**Comment by eregon** [comment]
@Atul9 let's go with `FrozenError` in the description for now. It's easy to globally search/replace after if needed :)

**Comment by Atul9** [comment]
@eregon okay

**Comment by andrykonchin** [comment]
I would chose interpolation
```ruby
it "raises a #{frozen_error_class} if the array if frozen"
```

**Comment by eregon** [comment]
@andrykonchin That's smart :)
In general it's bad to have variable parts in the spec descriptions, because then they cannot be tagged.
But since `frozen_error_class` only changes per Ruby version it would be fine.
