### ISSUE TITLE
BigDecimal & YAML (Pysch)

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/spec#587]
@eregon

While testing a build of 2.3.6 with all default gems updated/installed, I had spec failures in BigDecimal & YAML (Psych).  I believe some of the tests are using `ruby_version_is` to check for API changes.  Since most (all?) default gems have internal version numbers, would PR's be accepted to use those instead?

Thanks, Greg

**Comment by eregon** [comment]
So you're testing a custom build of 2.3.6 with updated default gems?

I suppose it's fine, although I don't know how much that is supported (I could imagine some of these gems becoming incompatible with older versions).
How can you retrieve the running version of BigDecimal and Psych?

Please open a PR and let's discuss there to see the changes concretely.

**Comment by MSP-Greg** [comment]
Using YAML, it's just a matter of replacing [`library/yaml/tagurize_spec.rb:4`](https://github.com/ruby/spec/blob/83063a312d81113ebe5cfe8f90836da4024dcd35/library/yaml/tagurize_spec.rb#L4)
```ruby
ruby_version_is ''...'2.5' do
```

with
```ruby
if YAML::VERSION < '3.0.0'
```

Luckly, both `YAML` (Psych) and `BigDecimal` have `VERSION` constants.

Question - is there a more 'spec' way of doing it?  If not, I'll do a PR...

Thanks, Greg

**Comment by eregon** [comment]
Using a [custom guard](https://github.com/ruby/spec/blob/master/CONTRIBUTING.md#guards) instead of `if` is better here:
```ruby
guard -> { YAML::VERSION < '3.0.0' } do
  ...
end
```

**Comment by MSP-Greg** [comment]
Thanks.  That's helpful, and I re-read the doc (it was a while ago)...

Question - I've added a method as below:
```ruby
module DefaultGem
  # hash to hold found values
  @gem_vers = {}

  # returns the version of installed default gem
  def self.vers(gem)
    if @gem_vers.key? gem
      @gem_vers[gem]
    else
      # create streamUI with io
      sio_in, sio_out, sio_err = StringIO.new, StringIO.new, StringIO.new
      strm_io = Gem::StreamUI.new(sio_in, sio_out, sio_err, false)
      cmd = Gem::Commands::ListCommand.new
      cmd.ui = strm_io

      # load argument & execute
      hsh = {:args => %W[#{gem}]}
      cmd.merge_options hsh
      cmd.execute
      @gem_vers[gem] = sio_out.string[/([^( ]+)\)/,1]
    end
  end
end
```

If something like this was added, where would you put it?  Here, `mspec`, etc...

By using the method, bigdecimal is working correctly with ruby 2.3.3, 2.4.3, and trunk, along with my 'hot-rodded' version of 2.3.6.  BigDecimal has changed from `BigDecimal.ver` to `BigDecimal::VERSION`, and the only reliable way to track it is via the gem version.  For YAML, it's VERSION constant works fine.

The issue of version testing is messy.  I don't know what you want to support.  I came across the issue when trying to find which commit(s) solved an issue/fix that was being considered for backporting.

My build system has some patch selection based on version, but I need to improve it.  In an ideal world, I would like it to correctly build ruby with the repo/src checked out at any commit.

I assume you'd like spec/mspec to work with all ruby branch heads, not sure about custom builds or in-between checkout's...

**Comment by eregon** [comment]
Loading RubyGems in mspec is definitely not ideal, as mspec tries to stay as simple as possible with the fewest dependencies (even on stdlib).

Long term, I think we should move these specs in the separate repos for gemified stdlibs.
Then at least the tests/specs should be up-to-date with the code.
But running those tests/specs might become more complex.

I only try to make ruby/spec work with latest supported minor versions of Ruby and trunk, to limit efforts.

For this specific case of BigDecimal, what specs are failing?
It's OK to check sth like `defined?(BigDecimal.ver)` or so.

**Comment by MSP-Greg** [comment]
> For this specific case of BigDecimal, what specs are failing?

Using the current master, result is:
```
52 files, 294 examples, 5499 expectations, 6 failures, 1 error, 0 tagged
```

Using my patches, result is:
```
52 files, 293 examples, 5880 expectations, 0 failures, 0 errors, 0 tagged
```

Log file attached.  Note that 381 specs are not run...

Thanks, Greg
[bigdecimal_spec_results.txt](https://github.com/ruby/spec/files/1678431/bigdecimal_spec_results.txt)

**Comment by eregon** [comment]
Please open a PR, I think we can guard specs easily enough, not so many seem to fail.
We can use some helper method in `library/bigdecimal/fixtures/classes.rb` if the logic to get the version is more involved.

**Comment by MSP-Greg** [comment]
Thanks for the suggestion.  I changed the code for the above method, it now opens the gemspec file and uses a regex to find the version.  So, no longer need to load RubyGems...

I'll do a PR today or tomorrow.  Greg

**Comment by eregon** [comment]
@MSP-Greg Could you do a PR if this is still an issue?

**Comment by MSP-Greg** [comment]
@eregon

At the time, I think I was building 2.3.6 for an application with embedded Ruby, which would not work with 2.4+ due to Integer issues.

Given that 2.3 is unsupported, I'll close...
