### ISSUE TITLE
Range/flip-flop precedence

### ISSUE THREAD

**Issue by willglynn** [ruby/spec#589]
I noticed [this](https://github.com/ruby/spec/blob/v1.x/language/precedence_spec.rb#L342-L350) in `language/precedence_spec.rb`:

```ruby
# XXX: this is commented now due to a bug in compiler, which cannot
# distinguish between range and flip-flop operator so far. zenspider is
# currently working on a new lexer, which will be able to do that.
# As soon as it's done, these piece should be reenabled.
#
#  it ".. ... have higher precedence than ? :" do
#    (1..2 ? 3 : 4).should == 3
#    (1...2 ? 3 : 4).should == 3
#  end
```

This section entered the repo via 6c1c34a6bbf28b55e59bc6a97a1211718082d3e7, almost ten years ago, so while I don't _quite_ know what it's talking about, the original rationale for leaving it commented out seems likely to be incorrect by now.

Should this be re-enabled? Removed entirely? Left commented out with an updated explanation?

**Comment by eregon** [comment]
Thanks for the report, I re-enabled the spec in a23caca.
It seems like it was a bug in Rubinius at the time.
