### ISSUE TITLE
Add check in CI that no unexpected top-level constant is added by specs

### ISSUE THREAD

**Issue by eregon** [ruby/spec#613]
See https://github.com/ruby/spec/pull/612#discussion_r202647216 for instance.

I also recently discovered some `include Socket::Constants` which is definitely wrong:
https://github.com/ruby/spec/blob/181dd65d49b4636080ed22c7054abddafec8471d/library/socket/socket/listen_spec.rb#L4

The check should discover constants added at the top-level before `describe` like:
```ruby
require_relative '../../spec_helper'

class StringSubclass < String
end
# or
include Socket::Constants

describe "foo" do
   ...
```

but also constants added by spec examples (`it`):
```ruby
  it "bar" do
    StringSubclass = Class.new(String)
  end
```

**Comment by andrykonchin** [comment]
It looks pretty simple with [Module.constants](https://ruby-doc.org/core-2.2.0/Module.html#method-c-constants). I guess new top-level constant should result in warning?

**Comment by andrykonchin** [comment]
> Maybe this check should be optional, much like CHECK_LEAKS.

Looks good

There are quite a few specs which require core/std libs or fixture file with top-level constant right in `it`'s block like [here](https://github.com/ruby/spec/blob/master/core/main/using_spec.rb#L26) and [here](https://github.com/ruby/spec/blob/master/library/yaml/dump_spec.rb#L38)

Does it make sense to move these calls (of `require`) to the top level?

**Comment by andrykonchin** [comment]
> Would you like to give a shot at implementing this feature in MSpec+ruby/spec, since you seem interested?

Yes. Later this week.

**Comment by eregon** [comment]
https://github.com/ruby/mspec/pull/41 was (finally) merged, thanks @andrykonchin!
I'll document this in ruby/spec `CONTRIBUTING.md`.

**Comment by eregon** [comment]
Related: other leak checks now also cause errors (instead of just warnings), to be noticed early and avoid regressions with https://github.com/ruby/mspec/commit/2ee56619e743f1e9b913ca8939f462b86d262e94

**Comment by eregon** [comment]
Documented in https://github.com/ruby/spec/commit/4997df355c89138cec0b645c238940d06300e103
