### ISSUE TITLE
core/ kernel/autoload_spec.rb - 4 failures when run alone?

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/spec#622]
While working on multi & random, I found failures in [`core/kernel/autoload_spec.rb`](https://github.com/ruby/spec/blob/c60025c9776b9fc36605c1d47757375e23cdf424/core/kernel/autoload_spec.rb).  When I then ran it alone, I also had 4 failures.

Wondering if anyone can repro that?

Not being that familiar with scoping in MSpec, I'm not sure what the issue is.  The attached patch does fix the issue (added a txt extension for GitHub).

[core-kernel-autoload_spec.rb.patch.txt](https://github.com/ruby/spec/files/2448622/core-kernel-autoload_spec.rb.patch.txt)

**Comment by eregon** [comment]
IIRC it works fine when run alone, but maybe there was a recent regression.
Moving the autoload? calls in before :all is not quite correct as we should call autoload? once per spec example (`it`).

Could you share the log of the failures?

And could someone confirm it works fine when run alone on Linux or macOS? (I can't myself)

**Comment by MSP-Greg** [comment]
@eregon 

Thought you were AFK...  Running Windows right now?

All four return nil, but only when run alone or random, not when run non-random.  Also, using the ruby version, the files looked the same (same number of lines), but I didn't check...  Log below:
```
PS> ruby --disable=gems -rdevkit ../mspec/bin/mspec -j -H -V -T "--disable=gems" core/
kernel/autoload_spec.rb
ruby 2.6.0dev (2018-10-04 trunk 64913) [x64-mingw32]
[1/1]  A    22  core/kernel/autoload_spec.rb


1)
Kernel#autoload when called from included module's method the autoload is reacheable from the class too FAILED
Expected nil
to equal "C:/Greg/GitHub/ruby/spec/ruby/core/kernel/fixtures/autoload_from_included_module.rb"

C:/Greg/GitHub/ruby/spec/ruby/core/kernel/autoload_spec.rb:76:in `block (3 levels) in <top (required)>'
C:/Greg/GitHub/ruby/spec/ruby/core/kernel/autoload_spec.rb:16:in `<top (required)>'

2)
Kernel#autoload when called from included module's method setups the autoload on the included module FAILED
Expected nil
to equal "C:/Greg/GitHub/ruby/spec/ruby/core/kernel/fixtures/autoload_from_included_module.rb"

C:/Greg/GitHub/ruby/spec/ruby/core/kernel/autoload_spec.rb:72:in `block (3 levels) in <top (required)>'
C:/Greg/GitHub/ruby/spec/ruby/core/kernel/autoload_spec.rb:16:in `<top (required)>'

3)
Kernel.autoload when called from included module's method setups the autoload on the included module FAILED
Expected nil
to equal "C:/Greg/GitHub/ruby/spec/ruby/core/kernel/fixtures/autoload_from_included_module2.rb"

C:/Greg/GitHub/ruby/spec/ruby/core/kernel/autoload_spec.rb:138:in `block (3 levels) in <top (required)>'
C:/Greg/GitHub/ruby/spec/ruby/core/kernel/autoload_spec.rb:101:in `<top (required)>'

4)
Kernel.autoload when called from included module's method the autoload is reacheable from the class too FAILED
Expected nil
to equal "C:/Greg/GitHub/ruby/spec/ruby/core/kernel/fixtures/autoload_from_included_module2.rb"

C:/Greg/GitHub/ruby/spec/ruby/core/kernel/autoload_spec.rb:142:in `block (3 levels) in <top (required)>'
C:/Greg/GitHub/ruby/spec/ruby/core/kernel/autoload_spec.rb:101:in `<top (required)>'

Finished in 0.314027 seconds

1 file, 22 examples, 23 expectations, 4 failures, 0 errors, 0 tagged
PS C:\Greg\GitHub\ruby\spec\ruby>```

**Comment by MSP-Greg** [comment]
@eregon

Attached is a patch that allows "-j -V -H' for parameters.  I'm sure it's all wrong, but I needed something that output filenames along with example count.  It's set up for the spec folder in ruby...

I've also got a ps1 file that drives a loop and splits STDOUT & STDERR to two different files, let me know if you'd like that.

[2018-10-05-mspec_multi.patch.txt](https://github.com/ruby/spec/files/2448710/2018-10-05-mspec_multi.patch.txt)

**Comment by eregon** [comment]
@MSP-Greg Can you still reproduce?

The patch above seems to change formatter stuff, but nothing about autoload specs.

**Comment by MSP-Greg** [comment]
@eregon 

Can't repo.  Just ran `../mspec/bin/mspec -j core/kernel` a few times against
```
ruby 2.7.0dev (2019-11-02T06:32:49Z master 772b0613c5)
```

It ran fine.  I'll close...  Sorry.

**Comment by eregon** [comment]
Great :)

**Comment by MSP-Greg** [comment]
@eregon

JFYI, I just tested locally, CI on AppVeyor runs in about an hour.  Conversely, a few years ago, I often had situations where CI would fail, but locally wouldn't.  Much less common today.

So, other than patches to get output like:
```
            PID Examples  Exp  File
[   1/3778]  B     2       2   command_line/dash_c_spec.rb
[   2/3778]  A     2       2   command_line/dash_a_spec.rb
[   3/3778]  B     3       3   command_line/dash_d_spec.rb
```

The only 'spec' patch I have is mentioned in:
https://bugs.ruby-lang.org/issues/16265
having to do with ssp ('Stack Smashing Protector')

Thanks for all your work on spec.
