### ISSUE TITLE
Buffer size is not larger than the pipe capacity on Linux ppc64le

### ISSUE THREAD

**Issue by odaira** [ruby/spec#626]
https://github.com/ruby/spec/blob/fc1cf69cea933e8e5ed942d49ca9eea518818633/core/io/syswrite_spec.rb#L58

The default pipe capacity of Linux ppc64le is 1048576 bytes, while that of Linux x86_64 is 65536 bytes.  This test does not work as intended on ppc64le.  I am not sure if we should simply increase `larger_than_pipe_capacity`, so I am raising this issue.

**Comment by eregon** [comment]
Thank you for the report.
I think it's fine to increase it to something like 2 megabytes.
@odaira   Could you make a PR for that?
