### ISSUE TITLE
Need finer-grained way to specify reserved signals

### ISSUE THREAD

**Issue by headius** [ruby/spec#659]
In the specs for Signal trap logic, there are a set of PlatformGuard lines used to specify the set of reserved signals on "ruby", "jruby" and "truffleruby". The spec proceeds to confirm that the unreserved signals can be handled and the reserved signals cannot.

Unfortunately this mechanism is not fine-grained enough for testing JRuby. Unlike the other implementations, JRuby can run on many different VMs, each of which may have different sets of reserved signals. For example, Eclipse OpenJ9 has a different and larger set of reserved signals.

Most of the JVMs also provide flags (like -Xrs or -XX:+ReduceSignalUsage) to reduce the number of signals used by the VM (usually with a performance impact). This mode is also valid for JRuby users, and we would like to be able to test it.

So it seems there needs to be a more general way for an implementation to configure at spec boot time what signals it expects to be available. I'm not sure the best mechanism to use to do that.

**Comment by eregon** [comment]
Thanks for the report.
Indeed, it's proving hard to test signals meaningfully.
The current intent is to make sure each signal is either overridable, reserved or "cannot be trap'd" per OS semantics (only SIGKILL and SIGSTOP in that last category).
The specs also try to document which signals on which Ruby implementation are in which category, e.g. to get an idea of which signal are portably overridable.

TruffleRuby also needs to deal with this multi-VMs, although currently it's just two VMs:
```ruby
    if PlatformGuard.implementation?(:truffleruby)
      if !TruffleRuby.native?
        reserved_signals += %w[SEGV ILL FPE USR1 QUIT]
      end
    end
```

So feel free to add extra checks in the `if PlatformGuard.implementation?(:jruby)`, e.g. by checking VM name and querying some system property if there is for `-Xrs`.

Or you could also check a set of signals potentially used by the VM, and then try to `trap` them and if that raises add them to the `reserved_signals` (and restore the trap handlers to original if `trap` succeeds). That way, they are detected automatically, at the risk of having more signals reserved than expected without noticing.

Does that answer your questions?

P.S.: My experience with `-Xrs` is it didn't really work well on HotSpot, but maybe that was fixed.

**Comment by eregon** [comment]
@headius Does that help you? Can we close this issue?

**Comment by eregon** [comment]
Fixed by 01b75cbfd021fc6db9036d8305583128d3d7b836, which avoids hardcoding which signals are reserved and instead checks each signal is either reserved or can be `Signal#trap`-ed.

**Comment by eregon** [comment]
Link to the last version listing reserved signals per implementation explicitly:
https://github.com/ruby/spec/blob/ebdf0d1b06b39374a85baaae53771449ab1fe3d7/core/signal/trap_spec.rb#L118-L133

(I've been looking for it a few times, it's useful in terms of documentation and to get an overview)

**Comment by ioquatix** [comment]
Signal handling is an important part of multi-process servers.

- USR1 in particular is one which is commonly used for startus.
- HUP for restarting.
- INT for graceful shutdown.
- TERM for immediate shutdown.

Some basic guarantees about what signals are safe across all platforms would be helpful.

**Comment by eregon** [comment]
`USR1` is reserved by HotSpot as you can see above (on JRuby and on TruffleRuby in `--jvm` mode), the others are fine, I think no common JVM reserves them.

Note that the default `INT` handler on JRuby doesn't have the same semantics as on MRI and TruffleRuby (i.e. to raise an `Interrupt` exception on the main thread). Instead it's just the default handler from the JVM which just kills the entire process but no Ruby exception: https://github.com/jruby/jruby/wiki/Signal-Handling
