### ISSUE TITLE
Remove or modify specs that reference RubyVM

### ISSUE THREAD

**Issue by headius** [ruby/spec#662]
Recent commits have continued to add specs that reference the CRuby-specific `RubyVM` class. I believe these specs should either be moved to a CRuby-specific location or modified to not reference CRuby-specific internal features.

Here are the relevant references I found:

Specs for CRuby's experimental JIT (should not be in ruby/spec at all):
* https://github.com/ruby/spec/blob/023b5a543b33cbba96d67c8f1fbb2a6c9bab92d3/command_line/feature_spec.rb#L41

Related mspec config line:
* https://github.com/ruby/spec/blob/5f4cc5c32f3a1f5085bbd5bdcefd1a4bc516d94f/default.mspec#L57

Instruction sequence specs, which will never pass anywhere but CRuby (or on impls derived almost entirely from CRuby):
* https://github.com/ruby/spec/blob/85e616105d88838704288cda864a8ac89d420d5e/core/tracepoint/instruction_sequence_spec.rb#L22

Additional expectations for tracepoint enable spces:
* https://github.com/ruby/spec/blob/e81b3cd8d156a954602a7dbac748b7a061614291/core/tracepoint/enable_spec.rb#L252

No alternative implementation currently has plans to support either the --jit flag (or at least it won't do what it does in CRuby) or the RubyVM namespace. Any specs relating to CRuby-specific features should live in CRuby's repository only, and not be part of the implementation burden for alternative impls.

**Comment by eregon** [comment]
Generally agreed.
Especially, `RubyVM` should not be required to pass all specs.

I think some parts could be portable, e.g., the `--enable-jit/--disable-jit` command-line flags.
Do you think it would make sense other implementations support this "feature" too, or should we just remove the spec?

* `spec/command_line/feature_spec.rb`: I already changed the `feature_spec.rb` to be more general in MRI's copy, so it will be here with the next synchronization: https://github.com/ruby/ruby/commit/990df873029a632c06dee9de9768bda8400fe922.

* `spec/default.mspec`: this is a way for MRI to tag specs that currently fail with MJIT. I don't think it hurts anything, does it? (it should only be used as `without_feature :mjit`, there are a couple misuses I'll fix).

* `spec/core/tracepoint/instruction_sequence_spec.rb` and `spec/core/tracepoint/enable_spec.rb`: Yes, I agree and was thinking the same in https://github.com/ruby/spec/pull/657#discussion_r254476034, I'll remove them.

**Comment by eregon** [comment]
@headius I addressed the 4 cases you mentioned, so there are no more `RubyVM` on `master`.
Therefore I'll close this issue, thank you for reporting it.

I'd like to have your opinion on whether `--enable-jit/--disable-jit` should be portable. For now I removed the spec because it's rather unclear.

**Comment by chrisseaton** [comment]
> No alternative implementation currently has plans to support either the `--jit` flag (or at least it won't do what it does in CRuby)

We were briefly thinking about supporting `--enable-jit` and `--disable-jit` in TruffleRuby, with obvious semantics, but decided against it in the end.

**Comment by eregon** [comment]
Related, I'd like to clarify the naming of `RubyVM` and rename it to `CRuby` for clarity: https://bugs.ruby-lang.org/issues/15743

**Comment by headius** [comment]
We agree that supporting a general JIT option is unlikely to be valuable to users; we default to JIT and they don't, and tuning beyond that really should be done in a per-impl way. We already have to support enough weird flags!
