### ISSUE TITLE
It should be easier to measure implementation completeness

### ISSUE THREAD

**Issue by chrisseaton** [ruby/spec#667]
As a Ruby implementor I'd like to be able to measure how complete a Ruby implementation is, using the Ruby Spec Suite, in order to know where I need to do more work.

This is complicated for several reasons:

* Each implementation has a different version of the specs
* Each implementation has a different way of running the specs
* Some missing features show up as a lower number of examples (such as `fork`) so don't lower the percentage passing when they don't work

If you run the specs in each implementation you'll get a wildly different number of assumptions. I'm not sure what the target number of assumptions to pass is.

I think we should possibly get rid of the 'feature' functionality, and count `fork` examples which don't run as failures, getting implementations to tag them as we do other failures.

I think we should somehow make it easier to run a set of implementations against the same specs. The acceptance criteria should be that the number of examples is exactly the same when the same specs are run against different implementations. Then we can measure how far each implementation gets to that number.

I think we should possibly build a tool which helps you identify gaps in completeness. As well as knowing '98% compatibility' I want to know 'and most of that is in core/string and core/array' or something like that.

I'm not looking to game the system or compete to up a number for the sake of it, but the fact that I can't even seem to determine what 100% of the Ruby specs is makes me think something isn't as good as it could be.

**Comment by eregon** [comment]
Currently there are a few MSpec "features":
https://github.com/ruby/spec/blob/ee612d7d5bfefb7b16051cff2c6278e571d70cc7/default.mspec#L52-L57

I agree most are not very useful.
Every serious Ruby implementation needs to implement Fiber and Encoding.

`with_feature :fork` is only used in 11 `core` spec files. It's probably OK to count those as failures on implementations without `fork`.

MJIT guards could be done with `guard_not -> { defined?(RubyVM::MJIT) && RubyVM::MJIT.enabled? } do`, although that's rather long.
Much better would be to simply use tags files for MJIT, like other implementations do.
What do you think, @k0kubun?

Note that even by removing features, I don't expect the number of spec examples to be constant across Ruby implementations.

Here is a simple example where `it` examples are created dynamically:
https://github.com/ruby/spec/blob/ee612d7d5bfefb7b16051cff2c6278e571d70cc7/core/process/clock_gettime_spec.rb#L12
Maybe a way to solve that is making it a single `it` example, but provide a new method to provide extra debugging information to know which constant failed.
Note that a single example means it's no longer possible to tag just one constant case, so it's a trade-off.

Of course, spec examples will never be constant on different operating systems, machines, etc as a fair bit of specs depend on the running environment. But I guess this is fine for your purpose?

**Comment by k0kubun** [comment]
> Much better would be to simply use tags files for MJIT, like other implementations do.
> What do you think, @k0kubun?

I do not follow the context. What's tags file? Why is `with_feature :mjit` not sufficient?

**Comment by eregon** [comment]
@k0kubun Sorry, I should have included more context. I'll make a PR on ruby/ruby to show the proposed change more clearly.

**Comment by eregon** [comment]
I now removed almost all features from ruby/spec master (see the linked commits on this issue: fiber_library, fiber, fork, encoding).

For MJIT I removed specs which were incorrect anyway and replaced the only spec left using it with a `guard_not`.

Remaining are the [readline feature](https://github.com/ruby/spec/blob/master/library/readline/spec_helper.rb) and the [socket features](https://github.com/ruby/spec/blob/master/library/socket/spec_helper.rb).
Both could be replace with `guard -> { ... } do`. However, whether these guards pass will inherently rely on the implementation exposing Socket constants and a Readline module.
I think it's not reasonable to assert that these features work on a given set of operating systems, as they likely change per version, OS configuration, etc.

**Comment by enebo** [comment]
@eregon am I wrong but I thought opal was using ruby/spec and did not support m17n?

**Comment by eregon** [comment]
@enebo Indeed, I think Opal does not support encoding. Opal already has a system to exclude specs, so I assume that can be used to easily skip problematic specs (e.g., https://github.com/opal/opal/blob/master/spec/filters/unsupported/string.rb).
The main reason here is: It's not kept up-to-date, everyone adding specs assumes there are Encodings now in Ruby. I don't think anyone added a `with_feature :encoding do` in years to ruby/spec, so it's not maintained, incorrect, and the ability to tag/exclude specs is more general.

**Comment by enebo** [comment]
@eregon good point about people not knowing about needing to add encoding feature and so long as Opal is already maintaining their own excludes that seems doubly reasonable.

**Comment by eregon** [comment]
FWIW, Opal seems to support a fair bit of Encoding nowadays, so these `with_feature :encoding do` guards didn't have much value for Opal either (https://github.com/opal/opal/pull/1977 for details).

**Comment by eregon** [comment]
@chrisseaton Back to the original issue;
To get the same numbers of examples, we at least need to have the same specs, so either:
* Running the alternative implementation's copy of the specs, for both the impl and MRI.
* Using the version of specs of a specs update/synchronization, then all copies of ruby/spec are identical, but this is only available around once a month.

Basically, we need the implementation's tags to run specs without failures, so we need to use the implementation's specs (since specs might have been added). MRI needs no tags, so it should pass all specs at any time.

Concretely, using the first alternative and the example of TruffleRuby, we're not far for `language` and `core`. Of course, we need to use:
* The same spec files.
* The same OS and OS configuration, so basically the same machine.
* The same `RUBY_VERSION` for both implementations (otherwise `ruby_version_is` would change the number of specs). I used latest TruffleRuby and MRI 2.6.2 here.

`language`:
```
$ jt test :language
70 files, 2338 examples, 4065 expectations, 0 failures, 0 errors, 56 tagged

$ cd spec/ruby && mspec :language
70 files, 2338 examples, 4199 expectations, 0 failures, 0 errors, 0 tagged
```
Same number of examples.
Of course, there are less expectations because some examples are tagged.
Anyway, the number of expectations is not a good metric to quantify compatibility, rather the number of passing examples (`examples - tagged`) is.

`:core`:
```
$ jt test fast :core
1867 files, 20675 examples, 66246 expectations, 0 failures, 0 errors, 1484 tagged

$ cd spec/ruby && mspec :core
1867 files, 20674 examples, 149128 expectations, 0 failures, 0 errors, 0 tagged
```
They are more examples tagged on TruffleRuby here since I excluded slow specs.
The number of examples almost matches, there is just 1 example more for TruffleRuby which we should investigate.

**Comment by eregon** [comment]
FWIW, here is the output for running `:core` specs on TruffleRuby (including slow specs):
```
$ jt test :core
1867 files, 20675 examples, 67565 expectations, 0 failures, 0 errors, 1187 tagged
```

**Comment by chrisseaton** [comment]
We could just have a system for co-ordinating a run of the specs, even if it isn't easily possible all the time.

We we would:

* Pick a release of each Ruby implementation
* Get all their tags on that release commit
* Run against the latest version of specs
* Add new tags as needed
* Look at the numbers

That combined with work to make tags the only way to exclude specs, would give a global view.

**Comment by eregon** [comment]
We could do that, but we still need the 3 conditions mentioned [above](https://github.com/ruby/spec/issues/667#issuecomment-493702769).
For instance, there is currently no release of JRuby with Ruby 2.6.2 (or 2.6.3) compatibility (JRuby 9.2.7.0 targets Ruby 2.5.3).

> Add new tags as needed

This is not necessary, as long as specs error out cleanly and don't e.g., hang or kill the process, they'll just be counted as `errors` or `failures`, which we can sum with `tagged`.
Adding tags from the output is easy if wanted, with `mspec/tool/tag_from_output.rb`.

All the 5 steps are possible today. What is missing or what would you like automated?

> combined with work to make tags the only way to exclude specs

That does not seem tractable for platform-dependent or version-dependent guards, though, as said above. There are no guards for Ruby implementations though, which should be what matters here.
But if the Ruby implementation define less `Socket` constants (see [this](https://github.com/ruby/spec/blob/a019ab59e1ad9fb4c863e072282328bc03f7bf4d/library/socket/spec_helper.rb)), it can affect the number of examples. I don't know how to solve that.
We can compare what specs are run for instance by comparing the output of `mspec -fs` between runs on different Ruby implementations.

**Comment by eregon** [comment]
The 1 spec example difference for core specs between TruffleRuby and MRI is caused by Signal#trap specs:
```diff
--- mri.specs
+++ truffleruby.specs

-- raises ArgumentError for reserved signal: SIGBUS
+- raises ArgumentError for reserved signal: SIGUSR1
+- raises ArgumentError for reserved signal: SIGQUIT
```

due to having one more reserved signal on TruffleRuby JVM:
https://github.com/ruby/spec/blob/a019ab59e1ad9fb4c863e072282328bc03f7bf4d/core/signal/trap_spec.rb#L121-L133

This the only spec using `PlatformGuard.implementation?` and changing the number of examples based on it. I'll try to find a way to make the number of examples constant, and yet have useful error message when one fails.

**Comment by eregon** [comment]
Those specs related to #659 BTW.

**Comment by eregon** [comment]
With a couple more fixes, I now have the exact same set of specs, in the same order for `:core`, with TruffleRuby and MRI:
```
$ jt mspec run -t ruby -Z -fs :core | tee mri.txt
$ jt mspec run -Z -fs :core | tee tr.txt
$ git diff --no-index mri.txt tr.txt
```
The full diff being:
```diff
diff --git a/mri.txt b/tr.txt
index 423c09b18b..582396372a 100644
--- a/mri.txt
+++ b/tr.txt
@@ -1,4 +1,4 @@
-ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
+truffleruby 20.0.0-beta.01-dev-01644d33, like ruby 2.6.2, Interpreted JVM [x86_64-linux]
 
 ARGF
 - is extended by the Enumerable module
@@ -29589,6 +29589,6 @@ Warning.warn
 - is called by Kernel.warn
 
 
-Finished in 1.130061 seconds
+Finished in 11.803000 seconds
 
 1871 files, 20459 examples, 0 expectations, 0 failures, 0 errors, 0 tagged
```
The same for `:language`:
```
 70 files, 2340 examples, 0 expectations, 0 failures, 0 errors, 0 tagged
```
and `:command_line`:
```
 29 files, 137 examples, 0 expectations, 0 failures, 0 errors, 0 tagged
```

`:capi` has 3 specs less on TruffleRuby (due to the Fixnum range):
```diff
diff --git a/mri.txt b/tr.txt
index 3e2a396651..2952bc9d58 100644
--- a/mri.txt
+++ b/tr.txt
@@ -1,4 +1,4 @@
-ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]
+truffleruby 20.0.0-beta.01-dev-01644d33, like ruby 2.6.2, Interpreted JVM [x86_64-linux]
 
 C-API Array function rb_Array
 - returns obj if it is an array
@@ -149,16 +149,13 @@ C-API Array function rb_ary_subseq
 - returns nil if the size is negative
 
 CApiBignumSpecs rb_big2long
-- converts a Bignum
 - raises RangeError if passed Bignum overflow long
 
 CApiBignumSpecs rb_big2ll
-- converts a Bignum
 - raises RangeError if passed Bignum overflow long
 
 CApiBignumSpecs rb_big2ulong
 - converts a Bignum
-- wraps around if passed a negative bignum
 - raises RangeError if passed Bignum overflow long
 
 CApiBignumSpecs rb_big2dbl
@@ -2121,6 +2118,6 @@ C-API Util function rb_sourceline
 - returns the current ruby file
 
 
-Finished in 7.406587 seconds
+Finished in 2.149000 seconds
 
-36 files, 1184 examples, 0 expectations, 0 failures, 0 errors, 0 tagged
+36 files, 1181 examples, 0 expectations, 0 failures, 0 errors, 0 tagged
```

Note that I'm running with `-Z`/`--dry-run` here but an actual run should give the same.

**Comment by chrisseaton** [comment]
I think form Benoit's last comment this is sufficiently fixed. If there's other things we want we should open new more specific issues.
