### ISSUE TITLE
String#[] specs should not make assertions about Range implementation

### ISSUE THREAD

**Issue by lopopolo** [ruby/spec#673]
This spec for `String#[]` defines mocks for `<=>` and `to_int` on objects used for constructing a `Range`. If the Ruby implementation (like, for example, mruby) does not call these methods when constructing `Range`s, the test fails.

https://github.com/ruby/spec/blob/94d98ff35192a88fd3e20786fc6acb22106b3789/core/string/shared/slice.rb#L256-L268

Can we change the spec to use a stub that doesn't validate call counts instead of a mock?

**Comment by lopopolo** [comment]
I still don't think the test will pass because it will blow up when constructing the range, but at least the mock will be satisfied.

**Comment by eregon** [comment]
Thank you for reporting this.
I'm unsure. I think the current spec tests behavior which is valid on "full" Ruby implementations like MRI, JRuby, TruffleRuby, Rubinius, etc.

What does MRuby do here? Maybe it's a missing feature or a bug in MRuby?

I think it's OK for MRuby to not pass all ruby/spec, it implements a subset of full Ruby implementations. So maybe we just need a simple way to exclude that spec when running on MRuby here.

**Comment by eregon** [comment]
> Can we change the spec to use a stub that doesn't validate call counts instead of a mock?

Right, we can drop the call counts, I don't mind that. PR welcome.
I'd just like to keep testing that `to_int` is called, because it's user-visible behavior.

**Comment by eregon** [comment]
It doesn't seem valuable to change this spec, which is useful to test "full" Ruby implementations.
Calling any of these methods more than expected could lead to incorrect behavior.
