### ISSUE TITLE
String#=~ does not assert that named capture groups are not extracted

### ISSUE THREAD

**Issue by lopopolo** [ruby/spec#676]
I ran into this while implementing [Artichoke](https://github.com/artichoke/artichoke).

**Comment by eregon** [comment]
Could you make a PR?

I'm also not sure what you mean exactly (did you have `$1` implemented as a view and mutating the base string would change `$1`?), so code would be easier :)

**Comment by lopopolo** [comment]
@eregon this section from the docs:

> Note: str =~ regexp is not the same as regexp =~ str. Strings captured from named capture groups are assigned to local variables only in the second case.

**Comment by eregon** [comment]
Right, and only if the regexp is a literal of course.

The existing spec regarding this is in
https://github.com/ruby/spec/blob/e912a8daeb9a7e4ea7360a0686c9c65815848b6c/language/match_spec.rb#L42-L49
PR welcome :smiley:

**Comment by eregon** [comment]
It seems to me specs about this are already fairly complete in spec/language/match_spec.rb.
I added an extra spec in 659d233c79f0ff8d0a243e5684a25afbcdc76edb
