### ISSUE TITLE
Add JSON specs from flori/json

### ISSUE THREAD

**Issue by lopopolo** [ruby/spec#677]
JSON gem has[ tests implemented in test-unit](https://github.com/flori/json/tree/master/tests).

https://github.com/artichoke/artichoke/issues/77 would be lower risk if JSON tests existed in ruby/spec.

It'd be nice if we could port these tests to MSpec. 😄

**Comment by eregon** [comment]
In general, specs for the standard library are less complete than the rest.
I think this makes sense with standard libraries becoming their own repositories, gems, with their own tests.

I think there is not a lot of value to convert an entire test suite from tests to specs or vice-versa.

I'm not against adding new standard library specs either and it does make sense for a number of them, but I suspect it might be easier and more valuable for library maintainers to have tests in the original repository.

So in this case I would recommend to run the original tests.
I think test-unit (or the subset actually used) shouldn't be too hard to support.

**Comment by eregon** [comment]
I think for `json` we should use the tests/specs inside that repository, and not duplicate them here (which would quickly become out of date, etc). So I will close this issue.

For the matter of being able to run them easily, maybe we could try to convince the json authors to convert tests to specs? No idea how realistic that is.

@hsbt also made it clear recently it's better for default gems to have tests/specs in the same repository as the implementation.
