### ISSUE TITLE
Regexp core tests do not include Regexp patterns with lookahead or back references

### ISSUE THREAD

**Issue by lopopolo** [ruby/spec#678]
Artichoke is attempting to create a hybrid Regexp engine and some components do not support lookahead or backreferences.

My naive implementation to wholesale replace oniguruma failed at a distance in `uri` specs.

**Comment by eregon** [comment]
The regular expression syntax is considered part of `language`/.

https://github.com/ruby/spec/blob/master/language/regexp/anchors_spec.rb has specs for lookaheads.
https://github.com/ruby/spec/blob/master/language/regexp/back-references_spec.rb has specs for backreferences.
And https://github.com/ruby/spec/blob/e912a8daeb9a7e4ea7360a0686c9c65815848b6c/language/regexp_spec.rb#L116-L118 has specs for named backreferences.

Generally, new Ruby implementations focus on `language` before `core`, so I would recommend trying to pass most language specs early on.
