### ISSUE TITLE
printf/sprintf/String#% specs are very limited

### ISSUE THREAD

**Issue by chrisseaton** [ruby/spec#68]
These methods could have the majority of specs shared between them as they do basically the same thing.

The quantity and organisation of the specs here is also very limited. Many of the examples I think come from other test setups and are just added with descriptions such as 'passes kstephens's tests'.

We could do with copying the example in the specs for Array#pack and String#unpack, where tests are heavily parameterised with a separate file for each format character and several levels of sharing and a larger number of much smaller tests.

**Comment by eregon** [comment]
Closed by #537, thank you @andrykonchin!
