### ISSUE TITLE
ENV method return values encodings expectations

### ISSUE THREAD

**Issue by BurdetteLamar** [ruby/spec#690]
Some of the specs for ENV check the encodings of returned strings (usually a name or value);  some don't.

Should more specs check this?  And how to know when it's appropriate?

**Comment by eregon** [comment]
Yes, it's generally a good idea to test the encoding of Strings returned by APIs, especially those interacting with process values like the environment.

Testing it for the most common ENV#[] method is important. Testing it for every Hash-like method of ENV seems redundant, it seems unlikely a method would return a String of a different encoding than what other ENV method return.

As usual, this is much easier to discuss on a specific case in a PR.

**Comment by BurdetteLamar** [comment]
Thanks, eregon.
