### ISSUE TITLE
MinGW 2.5.8 failure

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/spec#765]
I saw the commits in ruby/ruby, and came here.  I noticed the 2.5.8 fail, and also the 2.5.7 pass.  More weird stuff.  It involves some or all of the below code.  With 2.5.8, I think I was seeing a syntax error (?):

https://github.com/ruby/spec/blob/7289ea3e3c22fb41b58d072e966420845cca6e9e/core/binding/local_variable_set_spec.rb#L60-L69

1. I could repo it locally.
2. I revised the test, and it passed locally with 2.5.8, failed with 2.5.7.
3. I pushed to my fork, and 2.5.8 failed.
4. Locally and in CI, 2.6, 2.7 and head are all fine.

Will look at more later.  When local and CI behave differently...

**Comment by eregon** [comment]
Thanks for investigating this, I was puzzled why 2.5.8 fails and unfortunately there isn't much details in the [CI log](https://github.com/ruby/spec/runs/559460946) (we could do a run without `-j` to try to get more details).

Maybe something that would help is to wrap in `eval()` the Symbols, so a parsing error wouldn't prevent to load the file.
Maybe something changed in the parser?
Sounds like an unintended breaking change, and even weirder it only seems to happen on Windows.

**Comment by MSP-Greg** [comment]
> Maybe something changed in the parser?

Very possible.  I've never looked in spec, but I use Ripper more than YARD in https://msp-greg.github.io/, and Ripper changes have bit me a few times.

> Sounds like an unintended breaking change, and even weirder it only seems to happen on Windows.

Yeah, welcome to my world.  What I really hate is when local and CI behave differently.  I'll look at it later...

**Comment by MSP-Greg** [comment]
Reminder, I'm not a strong c type.  I looked at the code in proc.c, beyond my pay grade...

But, the following code works with Ruby 2.6 and later.  With Ruby 2.5.7 and 2.5.8, the 'Lambdas local_variable_set' iteration silently stops.  I checked each of the three values, I believe all behave the same.

See https://github.com/MSP-Greg/ruby-testing/runs/562393278.  JFYI, the STDOUT.flush calls were needed, otherwise the failing steps didn't show any output.

Would the below be an acceptable repo case for a ruby/ruby issue?

JFYI, when I first started working with Windows Ruby, only mswin builds were done, with no test-all or test-spec.  Both were added to 2.5, but MinGW builds/testing didn't start until 2.6.

```ruby
puts "\n#{RUBY_DESCRIPTION}\n\nDirect local_variable_set"

[:$0, :$~, :$_].each do |v|
  begin
    binding.local_variable_set(v, '')
  rescue => e
    puts "#{v}  #{e.class}"
  end
end

puts "\nLmabdas local_variable_defined?"
STDOUT.flush

[:$0, :$~, :$_].each do |v|
  a = -> (bind) do
    x = bind.local_variable_defined? v
    puts "#{v} defined? #{x}"
  end
  begin
    a[binding]
  rescue => e
    puts "#{v}  #{e.class}"
  end
end

puts "\nLambdas local_variable_get"
STDOUT.flush

[:$0, :$~, :$_].each do |v|
  a = -> (bind) do
    bind.local_variable_get(v)
  end
  begin
    a[binding]
  rescue => e
    puts "#{v}  #{e.class}"
  end
end

puts "\nLambdas local_variable_set"
STDOUT.flush

[:$0, :$~, :$_].each do |v|
  a = -> (bind) do
    bind.local_variable_set(v, '')
  end
  begin
    a[binding]
  rescue => e
    puts "#{v}  #{e.class}"
    STDOUT.flush
  end
end
```

**Comment by eregon** [comment]
:+1: I think this should be enough to report a bug to https://bugs.ruby-lang.org/, could you report it?

**Comment by MSP-Greg** [comment]
See https://bugs.ruby-lang.org/issues/16759

**Comment by eregon** [comment]
It's still failing: https://github.com/ruby/spec/runs/638859779?check_suite_focus=true
What should we do about this?

**Comment by MSP-Greg** [comment]
I'll have a look this weekend.  I've got two messages above about 2.5.x versions, I'll recheck (probably with Actions) to confirm what passes and what fails, then try to see what the cause is...

Thanks, and hope things are well.

**Comment by eregon** [comment]
I'll "allow failures" for 2.5.8 on Windows for now: 663cf3112c48f3377c900b264b313afa642570e5

**Comment by MSP-Greg** [comment]
Sorry, never replied.  Got frustrated, as my c skills are, at best, trivial.  Simple stuff only, so determining why only 2.5.8 on Windows is failing is way beyond my skill set...  Thanks.

**Comment by eregon** [comment]
I excluded Windows 2.5.8 from CI, I don't want to deal with this anymore and it's too confusing with `continue-on-error` in the UI: 440fea79f0d8cae566b0fa25708ba7810d65b3d4
