### ISSUE TITLE
Spec &nil

### ISSUE THREAD

**Issue by chrisseaton** [ruby/spec#771]
Spec passing `&nil` as a block argument. Doesn't seem to appear anywhere at all in specs, and it's not specifically tested in MRI, although it is used in two places in MRI code. My use-case was calling `super` but wanting to handle the block in my override.

Thanks to @noahgibbs https://twitter.com/codefolio/status/1274705180420902916

**Comment by eregon** [comment]
Would be good to test it in the context of `super(*args, &nil)` indeed.
For normal calls I'd guess it's already tested in many places, though `foo(&block)` with `block` being `nil`.

**Comment by eregon** [comment]
Could you do a PR?
I thinks a new spec example around https://github.com/ruby/spec/blob/ffb824547923b0dfa1dba135453da8b4d0484019/language/super_spec.rb#L90 would fit nicely.
