### ISSUE TITLE
Participate in Haktoberfest?

### ISSUE THREAD

**Issue by andrykonchin** [ruby/spec#791]
DigitalOcean changed the rules and to opt-in a public GitHub repository should have a topic `hacktoberfest`. Does it make sense for RubySpec to join the Hacktoberfest this year?

Unfortunately I don't have permissions to add the topic myself so if the answer is yes could anybody set it up?

https://www.youtube.com/watch?v=FxBv4FMcDgo&ab_channel=DigitalOcean

**Comment by eregon** [comment]
I'll add the topic and cross my fingers it doesn't lead to too much spam (which seems why that new rule was introduced).

I remember one of the past years hacktoberfest led to a lot of contributions but also of course a lot of PRs to review, so I would appreciate help from other ruby/spec maintainers & contributors for reviews :)

**Comment by eregon** [comment]
Done, and tweeted: https://twitter.com/eregontp/status/1313419067404021761
