### ISSUE TITLE
Windows mswin - ruby-loco failure - capi/thread_spec.rb

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/spec#808]
Not sure where to open an issue.  This happened in the most recent ruby-loco mswin build.  Full CI is not done on the mswin build in ruby/ruby.  Note that test-all did pass.  Looks like a 'c thing', 

Assume it's due to the recent commit [`Update to ruby/spec@4f59d86`](https://github.com/ruby/ruby/commit/148961adcd07)

See:
https://github.com/MSP-Greg/ruby-loco/runs/1302547223?check_suite_focus=true#step:18:6

Most of the 'error report' (reformatted):
```
RuntimeError: nmake.exe failed:
	 (echo EXPORTS && echo Init_thread_spec) > thread_spec-x64-mswin64_140.def
	 cl -nologo -I. -ID:/a/ruby-loco/ruby-loco/ruby-mswin/include/ruby-3.0.0/x64-mswin64_140
	 -ID:/a/ruby-loco/ruby-loco/ruby-mswin/include/ruby-3.0.0/ruby/backward
	 -ID:/a/ruby-loco/ruby-loco/ruby-mswin/include/ruby-3.0.0 -I.  -MD -Zi -W2 -wd4100 -wd4127
	 -wd4210 -wd4214 -wd4255 -wd4574  -wd4668 -wd4710 -wd4711 -wd4820 -wd4996  -we4028
	 -we4142 -we4047 -O2sy- -Zm600   -IC:/vcpkg/installed/x64-windows/include
	 -D_WIN32_WINNT=0x0600 -Fothread_spec.obj -c -Tcthread_spec.c
thread_spec.c
thread_spec.c(22): warning C4068: unknown pragma 'GCC'
thread_spec.c(76): warning C4068: unknown pragma 'GCC'
thread_spec.c(77): warning C4068: unknown pragma 'GCC'
thread_spec.c(79): error C2065: 'pid_t': undeclared identifier
thread_spec.c(79): error C2146: syntax error: missing ';' before identifier 'ret'
thread_spec.c(79): error C2065: 'ret': undeclared identifier
thread_spec.c(79): error C2064: term does not evaluate to a function taking 347 arguments
thread_spec.c(79): error C2143: syntax error: missing ')' before 'type'
thread_spec.c(79): error C2059: syntax error: ')'
thread_spec.c(80): error C2065: 'ret': undeclared identifier
thread_spec.c(82): warning C4068: unknown pragma 'GCC'
```

**Comment by eregon** [comment]
https://github.com/ruby/ruby/commit/99e067eac6fd2babcdd56142493ef0396744af85 should fix it, hopefully.
(there is also some discussion on https://github.com/ruby/spec/commit/3415df79eecd5fc519eccbee88938f2873b55fd9)

**Comment by MSP-Greg** [comment]
@eregon

Thanks.  I know in the past that you didn't want to test against master, but the master/head builds used today are fully tested, unlike many of the builds available before ruby/setup-ruby.  You did write many of the build scripts.  In some of the repos I'm involved with, we're running most of the master/head builds as a normal job, not 'allow-failure'.

Just a thought...

**Comment by eregon** [comment]
ruby/ruby does change specs directly (for the future Ruby version), so testing ruby-head in this repo would fail and it is fully expected. So there is no point to test it here because "fail" would not mean an issue, and solving that failure would just be duplicated work with changes in ruby/ruby.

**Comment by MSP-Greg** [comment]
You know better than I about how often changes move in each direction.

My point is that, assuming spec is synced between here and ruby/ruby, and all the builds available for CI are passing test-spec in ruby/ruby, using head builds here would show that new specs (added here) passed head CI.

But, this particular instance is different, because it's a platform (mswin) issue that would have been apparent if mswin builds were available for CI.  Maybe I need to consider building mswin builds for supported (not EOL) Ruby versions...

**Comment by eregon** [comment]
> My point is that, assuming spec is synced between here and ruby/ruby

They are, but only for a few hours once a month just after I synchronize. Any other time than that there might be changes in ruby/ruby that are not propagated to ruby/spec yet but are needed to make the specs pass on ruby master.

We'd need automatic synchronization ruby/ruby -> ruby/spec to really make this work, and that has never been implemented so far.
