### ISSUE TITLE
Enumerable#chunk spec incorrect 

### ISSUE THREAD

**Issue by macarthy** [ruby/spec#842]
Hi, newbie here be kind, :-) 

Re Enumerable#chunk
```
it "does not accept arguments" do
    e = EnumerableSpecs::Numerous.new(1, 2, 3)
    -> {
      e.chunk(1) {}
    }.should raise_error(ArgumentError)
  end
```
https://github.com/ruby/spec/blob/master/core/enumerable/chunk_spec.rb#L60

It appears that chunk does take an argument, and its kinda useful :-) 
its missing in all the docs too.  Rdocs too etc.  [DOCS](https://docs.ruby-lang.org/en/master/Enumerable.html#method-i-chunk)

```

"10001111111010110".chars.chunk(&:itself).map{|_,a| a.join}.join(", ") 
=> "1, 000, 1111111, 0, 1, 0, 11, 0"

```

I'd like to help but I'm lost as to how?

If I try running ../mspec/bin/mspec -t core/enumerable/chunk_spec.rb against 3.* on my machine I get 

``` 

$ core/enumerable/chunk_spec.rb /Users/macarthy/Dropbox/projects/mspec/bin/mspec-run
core/enumerable/chunk_spec.rb: line 1: require_relative: command not found
core/enumerable/chunk_spec.rb: line 2: require_relative: command not found
core/enumerable/chunk_spec.rb: line 4: describe: command not found
core/enumerable/chunk_spec.rb: line 5: before: command not found
core/enumerable/chunk_spec.rb: line 6: ScratchPad.record: command not found
core/enumerable/chunk_spec.rb: line 7: end: command not found
core/enumerable/chunk_spec.rb: line 9: it: command not found
core/enumerable/chunk_spec.rb: line 10: syntax error near unexpected token `('
core/enumerable/chunk_spec.rb: line 10: `    chunk = EnumerableSpecs::Numerous.new(1, 2, 3, 1, 2).chunk'

```

if i run the full suite it completes but I get webrick issues 

```

34)
An exception occurred during: loading /Users/macarthy/Dropbox/projects/spec/security/cve_2017_17742_spec.rb ERROR
LoadError: cannot load such file -- webrick
<internal:/Users/macarthy/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/macarthy/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/macarthy/Dropbox/projects/spec/security/cve_2017_17742_spec.rb:3:in `<top (required)>'
[\ | ==================100%================== | 00:00:00]      0F     34E

Finished in 237.584260 seconds

```

Thanks

**Comment by eregon** [comment]
> It appears that chunk does take an argument, and its kinda useful :-)

Can you show an example?

> "10001111111010110".chars.chunk(&:itself).map{|_,a| a.join}.join(", ") 

That's not "an argument" that's a block, or maybe "the block arguments".
So I think chunk takes no positional or keyword arguments, it only accepts a block.
I think that's the misunderstanding here, so I'll close, but feel free to comment if it's not that.

Re the command you swapped it around, mspec must be before the spec file.

Re webrick you can just `gem install webrick`.

**Comment by macarthy** [comment]
thanks
