### ISSUE TITLE
Please revert #dbff2dc 'Add Class#descendants'

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/spec#906]
See https://github.com/ruby/ruby/commit/3bd5f27f737c7d365b7d01c43d77a958c224ab16 'Remove Class#descendants'

**Comment by eregon** [comment]
Will do when I sync specs from CRuby master, if you need it earlier please make a PR removing that file.

**Comment by MSP-Greg** [comment]
RubyInstaller2 runs non Ruby master builds against this, I think it's the only issue, I'll check.

cc: @larskanis

**Comment by MSP-Greg** [comment]
See #907  Happy Holidays...

**Comment by larskanis** [comment]
Thanks @MSP-Greg for the PR! Yes it fails [here in rubyinstaller](https://github.com/oneclick/rubyinstaller2/runs/4637052326?check_suite_focus=true). It's fine if it could be fixed soon, but it's no showstopper if not.

**Comment by eregon** [comment]
Thanks for the PR, merged.
