### ISSUE TITLE
[Notice, please feel free to close it] Natalie 

### ISSUE THREAD

**Issue by rubyFeedback** [ruby/spec#944]
Hey benoit and others,

This is just a notice - please feel free to close this at any moment in time.

I only recently found Natalie. 

Tim's todo list is about 1124 tests failing, 6507 working already. :D

See here: https://natalie-lang.org/

I am a bit curious about natalie primarily from a GUI centric point of
view so I am watching it. So the whole point of this issue here is
really just to "cross thumbs that Natalie pases the specs soon"
and for the folks who maintain/run specs to also look out for those
up-and-coming folks trying to be ruby compatible!

**Comment by eregon** [comment]
I also learned about Natalie somewhat recently, it looks like a really cool and fun project.
It is however still a long way to be a fully compatible Ruby, there are 31417 examples in total, so 7038 / 31417 = 22.4% passing.
