### ISSUE TITLE
Safe navigation for square brackets

### ISSUE THREAD

**Issue by borela** [ruby/spec#946]
Currently we've got safe navigation:
```ruby
x&.y&.z
```
And if we need to use `[]`, we have to explicitly call:
```ruby
x&.[](:key)
```
Is there any proposal to combine the square brackets with safe navigation? For example:

```ruby
x&.[:key]
# Instead of
x&.[](:key)
```

**Comment by eregon** [comment]
Feature requests are at bugs.ruby-lang.org/ not here

**Comment by borela** [comment]
Will do, thanks.
